---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi mo7medsalah7/comingsoon-page
      ignore_errors: yes
      
    - name: build docker image using the Dockerfile
      command: docker build -t mo7medsalah7/comingsoon-page .

    - name: tagging docker image
      command: docker tag mo7medsalah7/comingsoon-page:latest new-repo:latest

    - name: Push Image to dockerhub
      command: docker push mo7medsalah7/comingsoon-page:latest

    - name: run container
      command: docker run -d --name web-container -p 5000:80 mo7medsalah7/comingsoon-page

